[build]
  command = "npm install --legacy-peer-deps && npm run build:web"
  publish = "dist"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[build.environment]
  NODE_VERSION = "18" 