services:
  - type: web
    name: slugger-app-backend
    env: node
    repo: https://github.com/username/slugger-repo
    branch: main
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    healthCheckPath: /api/ping
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: slugger-app-frontend
    env: static
    branch: main
    buildCommand: npm install && npm run build:web
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 